### ISSUE TITLE
Estimation: R Session Aborted

### ISSUE THREAD

**Issue by LusiXie** [plloydsmith/rmdcev#2]
Hi Pat, 

I finally got the admin access to a desktop and could successfully install the updated package with the newest version of R, R studio and R tools. The example you provide works. 

When I was trying to run the estimation with either 2017 or 2018 CWD survey data on R Studio, I kept running into "R Session Aborted" and had to started the new session with only one or two variables (e.g. CWD) at the first iteration. When I ran the estimation with all the variables as before, it seems like none of the models converged, with the error message: 
Error in chol.default(-H) : 
  the leading minor of order 43 is not positive definite
Error in attr(x, "names") <- as.character(value) : 
  'names' attribute [94] must be the same length as the vector [0]

I don't have the issue (only a couple times with SP 2018 survey data, not with 2017 data) with the previous version of the package - I still keep it in my laptop to run although the simulation can get pretty slow. 

Have you changed anything? 

Thanks.

Best,
Lusi

**Comment by plloydsmith** [comment]
Hi Lusi,

Yes, I changed the default prior settings for the parameters to be completely uninformative such that the rstan optimizing function will return the exact MLE estimates. The earlier package version had weakly informative priors (mostly normal(0,10)) hardcoded. You can toggle the priors on and off using the flat_prior option and you can tighten the priors if needed using the prior_parameter_sd options. Use ?FitMDCEV to get the full details on these options.

Pat

**Comment by LusiXie** [comment]
Perfect! After I changed the flat_prior option, it worked and results are similar as before. Welfare simulations also work. I'll keep playing with these options! Thanks for your hard work! 

Best,
Lusi
